# Generated by Django 4.0.6 on 2022-12-15 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('gas_verbruik', models.IntegerField()),
                ('stroom_verbruik', models.IntegerField()),
                ('gas_prijs_var', models.FloatField()),
                ('stroom_prijs_var', models.FloatField()),
                ('stroom_lever_prijs_var', models.FloatField()),
                ('gas_prijs_vast_dag', models.FloatField()),
                ('stroom_prijs_vast_dag', models.FloatField()),
                ('eigenaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
