# Generated by Django 4.0.6 on 2022-12-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esv', '0002_rename_eigenaar_house_bewoner'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='soort',
            field=models.CharField(default='hoekhuis', max_length=200),
            preserve_default=False,
        ),
    ]
