# Generated by Django 4.0.6 on 2022-12-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esv', '0003_house_soort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='soort',
            field=models.CharField(choices=[('hoekhuis', 'Hoekhuis'), ('tussenwoning', 'Tussenwoning'), ('2onder1kap', '2-onder-1-kap'), ('vrijstaand', 'Vrij staand')], default='green', max_length=14),
        ),
    ]
