# Generated by Django 4.0.6 on 2022-12-17 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esv', '0004_alter_house_soort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('prijs', models.IntegerField()),
                ('eigenaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Heatpump',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='esv.appliance')),
                ('cop', models.FloatField()),
                ('gbc', models.FloatField()),
            ],
            bases=('esv.appliance',),
        ),
        migrations.CreateModel(
            name='Homebattery',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='esv.appliance')),
                ('watt_cap', models.IntegerField()),
            ],
            bases=('esv.appliance',),
        ),
        migrations.CreateModel(
            name='Solarboiler',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='esv.appliance')),
                ('watt', models.IntegerField()),
                ('watt_cap', models.IntegerField()),
            ],
            bases=('esv.appliance',),
        ),
        migrations.CreateModel(
            name='Solarpannels',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='esv.appliance')),
                ('watt_cap_pp', models.IntegerField()),
                ('aantal', models.IntegerField()),
                ('jaar_van_aanschaf', models.IntegerField()),
                ('schaduw_factor', models.FloatField()),
            ],
            bases=('esv.appliance',),
        ),
    ]
