# Generated by Django 4.0.6 on 2022-12-23 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esv', '0006_scenariodb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='soort',
            field=models.CharField(choices=[('hoekhuis', 'Hoekhuis'), ('tussenwoning', 'Tussenwoning'), ('2onder1kap', '2-onder-1-kap'), ('vrijstaand', 'Vrij staand')], default='tussenwoning', max_length=14),
        ),
        migrations.CreateModel(
            name='Insulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soort', models.CharField(choices=[('dakisolatie', 'Dakisolatie'), ('vloerisolatie', 'Vloerisolatie'), ('spouwisolatie', 'Spouwisolatie'), ('glasisolatie', 'Glasisolatie')], default='vloerisolatie', max_length=14)),
                ('naam', models.CharField(max_length=200)),
                ('prijs', models.IntegerField()),
                ('rd', models.FloatField()),
                ('m2', models.IntegerField()),
                ('eigenaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
