# Generated by Django 4.0.6 on 2022-12-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esv', '0007_alter_house_soort_insulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariodb',
            name='saldering',
            field=models.FloatField(default=1),
        ),
    ]
