# Generated by Django 4.0.6 on 2022-12-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esv', '0008_scenariodb_saldering'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariodb',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scenariodb',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='esv.house'),
        ),
    ]
