# Generated by Django 4.0.6 on 2022-12-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esv', '0010_scenariomodel_delete_scenariodb'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='plafond',
            field=models.BooleanField(default=False),
        ),
    ]
