# Generated by Django 4.0.6 on 2022-12-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esv', '0011_scenariomodel_plafond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariomodel',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esv.house'),
        ),
    ]
