# Generated by Django 4.0.6 on 2022-12-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esv', '0012_alter_scenariomodel_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='insulation',
            field=models.ManyToManyField(to='esv.insulation'),
        ),
    ]
