# Generated by Django 4.0.6 on 2022-12-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esv', '0014_alter_house_soort'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='maandbedrag',
            field=models.IntegerField(default=0),
        ),
    ]
