# Generated by Django 4.0.6 on 2022-12-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esv', '0015_scenariomodel_maandbedrag'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='gasverbruik_na',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scenariomodel',
            name='stroomverbruik_na',
            field=models.IntegerField(default=0),
        ),
    ]
