# Generated by Django 4.0.6 on 2022-12-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esv', '0016_scenariomodel_gasverbruik_na_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='homebattery',
            field=models.ManyToManyField(to='esv.homebattery'),
        ),
    ]
