# Generated by Django 4.0.6 on 2023-01-03 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esv', '0017_scenariomodel_homebattery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_prijs_plafond', models.FloatField()),
                ('stroom_prijs_plafond', models.FloatField()),
                ('gas_plafond', models.IntegerField()),
                ('stroom_plafond', models.IntegerField()),
                ('saldering', models.FloatField(default=1)),
                ('eigenaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
