# Generated by Django 4.0.6 on 2023-01-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esv', '0019_alter_countryrules_saldering_alter_heatpump_gbc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariomodel',
            name='saldering',
        ),
    ]
