# Generated by Django 4.0.6 on 2023-01-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esv', '0020_remove_scenariomodel_saldering'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatpump',
            name='watt_cap',
            field=models.IntegerField(default=4500),
            preserve_default=False,
        ),
    ]
